name: flutter
on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.1.1
      with:
        flutter-version: '1.9.x'
        channel: 'dev'

    - run: flutter pub get
    - run: flutter test --coverage

    - run: sudo apt install -y lcov
    - run: genhtml coverage/lcov.info -o coverage

#    - run: sudo apt-get install apt-transport-https
#    - run: sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
#    - run: sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
#    - run: sudo apt-get update
#    - run: sudo apt-get install dart
#    - run: export PATH=$PATH:/usr/lib/dart/bin
#
#    - run: export PATH="$PATH":"$HOME/.pub-cache/bin"
#    - run: pub global activate --source git https://github.com/Rasarts/codemetrics.git
#    - run: pub run dart-codemetrics --begin-warning-complexity-number=4 --begin-error-complexity-number=8

  coverage:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install codemetrics
        run: pub global activate --source git https://github.com/Rasarts/codemetrics.git
      - run: touch pubspec.lock
      - name: Run codemetrics
        run: pub run dart-codemetrics --begin-warning-complexity-number=4 --begin-error-complexity-number=8
