name: flutter
on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.1.1
      with:
        flutter-version: '1.9.x'
        channel: 'dev'

    - name: Get packages
      run: flutter pub get

    - name: Run tests
      run: flutter test --coverage

    - run: flutter pub run dart-codemetrics --begin-warning-complexity-number=4 --begin-error-complexity-number=8

    - name: Install lcov
      run: sudo apt install -y lcov
    - name: Prepare coverage
      run: genhtml coverage/lcov.info -o coverage

#  coverage:
#
#    needs: [test]
#    runs-on: ubuntu-latest
#
#    container:
#      image:  google/dart:latest
#
#    steps:
#      - name: Install codemetrics
#        run: pub global activate --source git https://github.com/Rasarts/codemetrics.git
#      - name: Run codemetrics
#        run: pub run dart-codemetrics --begin-warning-complexity-number=4 --begin-error-complexity-number=8
